const categories = [
  {
    title: 'TOP STORIES',
    icon: 'star',
    category: 'top_stories',
  },
  {
    title: 'ALL NEWS',
    icon: 'folder',
    category: 'all_news',
  },
  {
    title: 'TRENDING',
    icon: 'adjust',
    category: 'trending',
  },
  {
    title: 'BOOKMARKS',
    icon: 'bookmark',
    category: '',
  },
];
const communities = [
  {n: 'select'},
  {n: 'Agarwal'},
  {n: 'Iyengar'},
  {n: 'Iyer'},
  {n: 'Kayastha'},
  {n: 'Khatri'},
  {n: 'Maratha'},
  {n: 'Nair'},
  {n: 'Rajput'},
  {n: 'Shia'},
  {n: 'Sunni'},
];
const createType = [
  {
    Type: 'Self',
  },
  {
    Type: 'Parent',
  },
  {
    Type: 'Sibling',
  },
  {
    Type: 'Relative',
  },
  {
    Type: 'Friend',
  },
];
const gender = [
  {
    type: 'male',
  },
  {type: 'female'},
];
const matrialStatus = [
  {
    Type: 'Unmarried',
  },
  {
    Type: 'Widow/Widower',
  },
  {
    Type: 'Divorced',
  },
  {
    Type: 'Seperated',
  },
];
const country = [
  {name: 'Afghanistan', code: 'AF'},
  {name: 'Åland Islands', code: 'AX'},
  {name: 'Albania', code: 'AL'},
  {name: 'Algeria', code: 'DZ'},
  {name: 'American Samoa', code: 'AS'},
  {name: 'AndorrA', code: 'AD'},
  {name: 'Angola', code: 'AO'},
  {name: 'Anguilla', code: 'AI'},
  {name: 'Antarctica', code: 'AQ'},
  {name: 'Antigua and Barbuda', code: 'AG'},
  {name: 'Argentina', code: 'AR'},
  {name: 'Armenia', code: 'AM'},
  {name: 'Aruba', code: 'AW'},
  {name: 'Australia', code: 'AU'},
  {name: 'Austria', code: 'AT'},
  {name: 'Azerbaijan', code: 'AZ'},
  {name: 'Bahamas', code: 'BS'},
  {name: 'Bahrain', code: 'BH'},
  {name: 'Bangladesh', code: 'BD'},
  {name: 'Barbados', code: 'BB'},
  {name: 'Belarus', code: 'BY'},
  {name: 'Belgium', code: 'BE'},
  {name: 'Belize', code: 'BZ'},
  {name: 'Benin', code: 'BJ'},
  {name: 'Bermuda', code: 'BM'},
  {name: 'Bhutan', code: 'BT'},
  {name: 'Bolivia', code: 'BO'},
  {name: 'Bosnia and Herzegovina', code: 'BA'},
  {name: 'Botswana', code: 'BW'},
  {name: 'Bouvet Island', code: 'BV'},
  {name: 'Brazil', code: 'BR'},
  {name: 'British Indian Ocean Territory', code: 'IO'},
  {name: 'Brunei Darussalam', code: 'BN'},
  {name: 'Bulgaria', code: 'BG'},
  {name: 'Burkina Faso', code: 'BF'},
  {name: 'Burundi', code: 'BI'},
  {name: 'Cambodia', code: 'KH'},
  {name: 'Cameroon', code: 'CM'},
  {name: 'Canada', code: 'CA'},
  {name: 'Cape Verde', code: 'CV'},
  {name: 'Cayman Islands', code: 'KY'},
  {name: 'Central African Republic', code: 'CF'},
  {name: 'Chad', code: 'TD'},
  {name: 'Chile', code: 'CL'},
  {name: 'China', code: 'CN'},
  {name: 'Christmas Island', code: 'CX'},
  {name: 'Cocos (Keeling) Islands', code: 'CC'},
  {name: 'Colombia', code: 'CO'},
  {name: 'Comoros', code: 'KM'},
  {name: 'Congo', code: 'CG'},
  {name: 'Congo, The Democratic Republic of the', code: 'CD'},
  {name: 'Cook Islands', code: 'CK'},
  {name: 'Costa Rica', code: 'CR'},
  {name: "Cote D'Ivoire", code: 'CI'},
  {name: 'Croatia', code: 'HR'},
  {name: 'Cuba', code: 'CU'},
  {name: 'Cyprus', code: 'CY'},
  {name: 'Czech Republic', code: 'CZ'},
  {name: 'Denmark', code: 'DK'},
  {name: 'Djibouti', code: 'DJ'},
  {name: 'Dominica', code: 'DM'},
  {name: 'Dominican Republic', code: 'DO'},
  {name: 'Ecuador', code: 'EC'},
  {name: 'Egypt', code: 'EG'},
  {name: 'El Salvador', code: 'SV'},
  {name: 'Equatorial Guinea', code: 'GQ'},
  {name: 'Eritrea', code: 'ER'},
  {name: 'Estonia', code: 'EE'},
  {name: 'Ethiopia', code: 'ET'},
  {name: 'Falkland Islands (Malvinas)', code: 'FK'},
  {name: 'Faroe Islands', code: 'FO'},
  {name: 'Fiji', code: 'FJ'},
  {name: 'Finland', code: 'FI'},
  {name: 'France', code: 'FR'},
  {name: 'French Guiana', code: 'GF'},
  {name: 'French Polynesia', code: 'PF'},
  {name: 'French Southern Territories', code: 'TF'},
  {name: 'Gabon', code: 'GA'},
  {name: 'Gambia', code: 'GM'},
  {name: 'Georgia', code: 'GE'},
  {name: 'Germany', code: 'DE'},
  {name: 'Ghana', code: 'GH'},
  {name: 'Gibraltar', code: 'GI'},
  {name: 'Greece', code: 'GR'},
  {name: 'Greenland', code: 'GL'},
  {name: 'Grenada', code: 'GD'},
  {name: 'Guadeloupe', code: 'GP'},
  {name: 'Guam', code: 'GU'},
  {name: 'Guatemala', code: 'GT'},
  {name: 'Guernsey', code: 'GG'},
  {name: 'Guinea', code: 'GN'},
  {name: 'Guinea-Bissau', code: 'GW'},
  {name: 'Guyana', code: 'GY'},
  {name: 'Haiti', code: 'HT'},
  {name: 'Heard Island and Mcdonald Islands', code: 'HM'},
  {name: 'Holy See (Vatican City State)', code: 'VA'},
  {name: 'Honduras', code: 'HN'},
  {name: 'Hong Kong', code: 'HK'},
  {name: 'Hungary', code: 'HU'},
  {name: 'Iceland', code: 'IS'},
  {name: 'India', code: 'IN'},
  {name: 'Indonesia', code: 'ID'},
  {name: 'Iran, Islamic Republic Of', code: 'IR'},
  {name: 'Iraq', code: 'IQ'},
  {name: 'Ireland', code: 'IE'},
  {name: 'Isle of Man', code: 'IM'},
  {name: 'Israel', code: 'IL'},
  {name: 'Italy', code: 'IT'},
  {name: 'Jamaica', code: 'JM'},
  {name: 'Japan', code: 'JP'},
  {name: 'Jersey', code: 'JE'},
  {name: 'Jordan', code: 'JO'},
  {name: 'Kazakhstan', code: 'KZ'},
  {name: 'Kenya', code: 'KE'},
  {name: 'Kiribati', code: 'KI'},
  {name: "Korea, Democratic People'S Republic of", code: 'KP'},
  {name: 'Korea, Republic of', code: 'KR'},
  {name: 'Kuwait', code: 'KW'},
  {name: 'Kyrgyzstan', code: 'KG'},
  {name: "Lao People'S Democratic Republic", code: 'LA'},
  {name: 'Latvia', code: 'LV'},
  {name: 'Lebanon', code: 'LB'},
  {name: 'Lesotho', code: 'LS'},
  {name: 'Liberia', code: 'LR'},
  {name: 'Libyan Arab Jamahiriya', code: 'LY'},
  {name: 'Liechtenstein', code: 'LI'},
  {name: 'Lithuania', code: 'LT'},
  {name: 'Luxembourg', code: 'LU'},
  {name: 'Macao', code: 'MO'},
  {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
  {name: 'Madagascar', code: 'MG'},
  {name: 'Malawi', code: 'MW'},
  {name: 'Malaysia', code: 'MY'},
  {name: 'Maldives', code: 'MV'},
  {name: 'Mali', code: 'ML'},
  {name: 'Malta', code: 'MT'},
  {name: 'Marshall Islands', code: 'MH'},
  {name: 'Martinique', code: 'MQ'},
  {name: 'Mauritania', code: 'MR'},
  {name: 'Mauritius', code: 'MU'},
  {name: 'Mayotte', code: 'YT'},
  {name: 'Mexico', code: 'MX'},
  {name: 'Micronesia, Federated States of', code: 'FM'},
  {name: 'Moldova, Republic of', code: 'MD'},
  {name: 'Monaco', code: 'MC'},
  {name: 'Mongolia', code: 'MN'},
  {name: 'Montserrat', code: 'MS'},
  {name: 'Morocco', code: 'MA'},
  {name: 'Mozambique', code: 'MZ'},
  {name: 'Myanmar', code: 'MM'},
  {name: 'Namibia', code: 'NA'},
  {name: 'Nauru', code: 'NR'},
  {name: 'Nepal', code: 'NP'},
  {name: 'Netherlands', code: 'NL'},
  {name: 'Netherlands Antilles', code: 'AN'},
  {name: 'New Caledonia', code: 'NC'},
  {name: 'New Zealand', code: 'NZ'},
  {name: 'Nicaragua', code: 'NI'},
  {name: 'Niger', code: 'NE'},
  {name: 'Nigeria', code: 'NG'},
  {name: 'Niue', code: 'NU'},
  {name: 'Norfolk Island', code: 'NF'},
  {name: 'Northern Mariana Islands', code: 'MP'},
  {name: 'Norway', code: 'NO'},
  {name: 'Oman', code: 'OM'},
  {name: 'Pakistan', code: 'PK'},
  {name: 'Palau', code: 'PW'},
  {name: 'Palestinian Territory, Occupied', code: 'PS'},
  {name: 'Panama', code: 'PA'},
  {name: 'Papua New Guinea', code: 'PG'},
  {name: 'Paraguay', code: 'PY'},
  {name: 'Peru', code: 'PE'},
  {name: 'Philippines', code: 'PH'},
  {name: 'Pitcairn', code: 'PN'},
  {name: 'Poland', code: 'PL'},
  {name: 'Portugal', code: 'PT'},
  {name: 'Puerto Rico', code: 'PR'},
  {name: 'Qatar', code: 'QA'},
  {name: 'Reunion', code: 'RE'},
  {name: 'Romania', code: 'RO'},
  {name: 'Russian Federation', code: 'RU'},
  {name: 'RWANDA', code: 'RW'},
  {name: 'Saint Helena', code: 'SH'},
  {name: 'Saint Kitts and Nevis', code: 'KN'},
  {name: 'Saint Lucia', code: 'LC'},
  {name: 'Saint Pierre and Miquelon', code: 'PM'},
  {name: 'Saint Vincent and the Grenadines', code: 'VC'},
  {name: 'Samoa', code: 'WS'},
  {name: 'San Marino', code: 'SM'},
  {name: 'Sao Tome and Principe', code: 'ST'},
  {name: 'Saudi Arabia', code: 'SA'},
  {name: 'Senegal', code: 'SN'},
  {name: 'Serbia and Montenegro', code: 'CS'},
  {name: 'Seychelles', code: 'SC'},
  {name: 'Sierra Leone', code: 'SL'},
  {name: 'Singapore', code: 'SG'},
  {name: 'Slovakia', code: 'SK'},
  {name: 'Slovenia', code: 'SI'},
  {name: 'Solomon Islands', code: 'SB'},
  {name: 'Somalia', code: 'SO'},
  {name: 'South Africa', code: 'ZA'},
  {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
  {name: 'Spain', code: 'ES'},
  {name: 'Sri Lanka', code: 'LK'},
  {name: 'Sudan', code: 'SD'},
  {name: 'Suriname', code: 'SR'},
  {name: 'Svalbard and Jan Mayen', code: 'SJ'},
  {name: 'Swaziland', code: 'SZ'},
  {name: 'Sweden', code: 'SE'},
  {name: 'Switzerland', code: 'CH'},
  {name: 'Syrian Arab Republic', code: 'SY'},
  {name: 'Taiwan, Province of China', code: 'TW'},
  {name: 'Tajikistan', code: 'TJ'},
  {name: 'Tanzania, United Republic of', code: 'TZ'},
  {name: 'Thailand', code: 'TH'},
  {name: 'Timor-Leste', code: 'TL'},
  {name: 'Togo', code: 'TG'},
  {name: 'Tokelau', code: 'TK'},
  {name: 'Tonga', code: 'TO'},
  {name: 'Trinidad and Tobago', code: 'TT'},
  {name: 'Tunisia', code: 'TN'},
  {name: 'Turkey', code: 'TR'},
  {name: 'Turkmenistan', code: 'TM'},
  {name: 'Turks and Caicos Islands', code: 'TC'},
  {name: 'Tuvalu', code: 'TV'},
  {name: 'Uganda', code: 'UG'},
  {name: 'Ukraine', code: 'UA'},
  {name: 'United Arab Emirates', code: 'AE'},
  {name: 'United Kingdom', code: 'GB'},
  {name: 'United States', code: 'US'},
  {name: 'United States Minor Outlying Islands', code: 'UM'},
  {name: 'Uruguay', code: 'UY'},
  {name: 'Uzbekistan', code: 'UZ'},
  {name: 'Vanuatu', code: 'VU'},
  {name: 'Venezuela', code: 'VE'},
  {name: 'Viet Nam', code: 'VN'},
  {name: 'Virgin Islands, British', code: 'VG'},
  {name: 'Virgin Islands, U.S.', code: 'VI'},
  {name: 'Wallis and Futuna', code: 'WF'},
  {name: 'Western Sahara', code: 'EH'},
  {name: 'Yemen', code: 'YE'},
  {name: 'Zambia', code: 'ZM'},
  {name: 'Zimbabwe', code: 'ZW'},
];
const nationality = [
  {nationality: 'Afghan'},
  {nationality: '\u00c5land Island'},
  {nationality: 'Albanian'},
  {nationality: 'Algerian'},
  {nationality: 'American Samoan'},
  {nationality: 'Andorran'},
  {nationality: 'Angolan'},
  {nationality: 'Anguillan'},
  {nationality: 'Antarctic'},
  {nationality: 'Antiguan or Barbudan'},
  {nationality: 'Argentine'},
  {nationality: 'Armenian'},
  {nationality: 'Aruban'},
  {nationality: 'Australian'},
  {nationality: 'Austrian'},
  {nationality: 'Azerbaijani, Azeri'},
  {nationality: 'Bahamian'},
  {nationality: 'Bahraini'},
  {nationality: 'Bangladeshi'},
  {nationality: 'Barbadian'},
  {nationality: 'Belarusian'},
  {nationality: 'Belgian'},
  {nationality: 'Belizean'},
  {nationality: 'Beninese, Beninois'},
  {nationality: 'Bermudian, Bermudan'},
  {nationality: 'Bhutanese'},
  {nationality: 'Bolivian'},
  {nationality: 'Bonaire'},
  {nationality: 'Bosnian or Herzegovinian'},
  {nationality: 'Motswana, Botswanan'},
  {nationality: 'Bouvet Island'},
  {nationality: 'Brazilian'},
  {nationality: 'BIOT'},
  {nationality: 'Bruneian'},
  {nationality: 'Bulgarian'},
  {nationality: 'Burkinab\u00e9'},
  {nationality: 'Burundian'},
  {nationality: 'Cabo Verdean'},
  {nationality: 'Cambodian'},
  {nationality: 'Cameroonian'},
  {nationality: 'Canadian'},
  {nationality: 'Caymanian'},
  {nationality: 'Central African'},
  {nationality: 'Chadian'},
  {nationality: 'Chilean'},
  {nationality: 'Chinese'},
  {nationality: 'Christmas Island'},
  {nationality: 'Cocos Island'},
  {nationality: 'Colombian'},
  {nationality: 'Comoran, Comorian'},
  {nationality: 'Congolese'},
  {nationality: 'Congolese'},
  {nationality: 'Cook Island'},
  {nationality: 'Costa Rican'},
  {nationality: 'Ivorian'},
  {nationality: 'Croatian'},
  {nationality: 'Cuban'},
  {nationality: 'Cura\u00e7aoan'},
  {nationality: 'Cypriot'},
  {nationality: 'Czech'},
  {nationality: 'Danish'},
  {nationality: 'Djiboutian'},
  {nationality: 'Dominican'},
  {nationality: 'Dominican'},
  {nationality: 'Ecuadorian'},
  {nationality: 'Egyptian'},
  {nationality: 'Salvadoran'},
  {nationality: 'Equatorial Guinean, Equatoguinean'},
  {nationality: 'Eritrean'},
  {nationality: 'Estonian'},
  {nationality: 'Ethiopian'},
  {nationality: 'Falkland Island'},
  {nationality: 'Faroese'},
  {nationality: 'Fijian'},
  {nationality: 'Finnish'},
  {nationality: 'French'},
  {nationality: 'French Guianese'},
  {nationality: 'French Polynesian'},
  {nationality: 'French Southern Territories'},
  {nationality: 'Gabonese'},
  {nationality: 'Gambian'},
  {nationality: 'Georgian'},
  {nationality: 'German'},
  {nationality: 'Ghanaian'},
  {nationality: 'Gibraltar'},
  {nationality: 'Greek, Hellenic'},
  {nationality: 'Greenlandic'},
  {nationality: 'Grenadian'},
  {nationality: 'Guadeloupe'},
  {nationality: 'Guamanian, Guambat'},
  {nationality: 'Guatemalan'},
  {nationality: 'Channel Island'},
  {nationality: 'Guinean'},
  {nationality: 'Bissau-Guinean'},
  {nationality: 'Guyanese'},
  {nationality: 'Haitian'},
  {nationality: 'Heard Island or McDonald Islands'},
  {nationality: 'Vatican'},
  {nationality: 'Honduran'},
  {nationality: 'Hong Kong, Hong Kongese'},
  {nationality: 'Hungarian, Magyar'},
  {nationality: 'Icelandic'},
  {nationality: 'Indian'},
  {nationality: 'Indonesian'},
  {nationality: 'Iranian, Persian'},
  {nationality: 'Iraqi'},
  {nationality: 'Irish'},
  {nationality: 'Manx'},
  {nationality: 'Israeli'},
  {nationality: 'Italian'},
  {nationality: 'Jamaican'},
  {nationality: 'Japanese'},
  {nationality: 'Channel Island'},
  {nationality: 'Jordanian'},
  {nationality: 'Kazakhstani, Kazakh'},
  {nationality: 'Kenyan'},
  {nationality: 'I-Kiribati'},
  {nationality: 'North Korean'},
  {nationality: 'South Korean'},
  {nationality: 'Kuwaiti'},
  {nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz'},
  {nationality: 'Lao, Laotian'},
  {nationality: 'Latvian'},
  {nationality: 'Lebanese'},
  {nationality: 'Basotho'},
  {nationality: 'Liberian'},
  {nationality: 'Libyan'},
  {nationality: 'Liechtenstein'},
  {nationality: 'Lithuanian'},
  {nationality: 'Luxembourg, Luxembourgish'},
  {nationality: 'Macanese, Chinese'},
  {nationality: 'Macedonian'},
  {nationality: 'Malagasy'},
  {nationality: 'Malawian'},
  {nationality: 'Malaysian'},
  {nationality: 'Maldivian'},
  {nationality: 'Malian, Malinese'},
  {nationality: 'Maltese'},
  {nationality: 'Marshallese'},
  {nationality: 'Martiniquais, Martinican'},
  {nationality: 'Mauritanian'},
  {nationality: 'Mauritian'},
  {nationality: 'Mahoran'},
  {nationality: 'Mexican'},
  {nationality: 'Micronesian'},
  {nationality: 'Moldovan'},
  {nationality: 'Mon\u00e9gasque, Monacan'},
  {nationality: 'Mongolian'},
  {nationality: 'Montenegrin'},
  {nationality: 'Montserratian'},
  {nationality: 'Moroccan'},
  {nationality: 'Mozambican'},
  {nationality: 'Burmese'},
  {nationality: 'Namibian'},
  {nationality: 'Nauruan'},
  {nationality: 'Nepali, Nepalese'},
  {nationality: 'Dutch, Netherlandic'},
  {nationality: 'New Caledonian'},
  {nationality: 'New Zealand, NZ'},
  {nationality: 'Nicaraguan'},
  {nationality: 'Nigerien'},
  {nationality: 'Nigerian'},
  {nationality: 'Niuean'},
  {nationality: 'Norfolk Island'},
  {nationality: 'Northern Marianan'},
  {nationality: 'Norwegian'},
  {nationality: 'Omani'},
  {nationality: 'Pakistani'},
  {nationality: 'Palauan'},
  {nationality: 'Palestinian'},
  {nationality: 'Panamanian'},
  {nationality: 'Papua New Guinean, Papuan'},
  {nationality: 'Paraguayan'},
  {nationality: 'Peruvian'},
  {nationality: 'Philippine, Filipino'},
  {nationality: 'Pitcairn Island'},
  {nationality: 'Polish'},
  {nationality: 'Portuguese'},
  {nationality: 'Puerto Rican'},
  {nationality: 'Qatari'},
  {nationality: 'R\u00e9unionese, R\u00e9unionnais'},
  {nationality: 'Romanian'},
  {nationality: 'Russian'},
  {nationality: 'Rwandan'},
  {nationality: 'Barth\u00e9lemois'},
  {nationality: 'Saint Helenian'},
  {nationality: 'Kittitian or Nevisian'},
  {nationality: 'Saint Lucian'},
  {nationality: 'Saint-Martinoise'},
  {nationality: 'Saint-Pierrais or Miquelonnais'},
  {nationality: 'Saint Vincentian, Vincentian'},
  {nationality: 'Samoan'},
  {nationality: 'Sammarinese'},
  {nationality: 'S\u00e3o Tom\u00e9an'},
  {nationality: 'Saudi, Saudi Arabian'},
  {nationality: 'Senegalese'},
  {nationality: 'Serbian'},
  {nationality: 'Seychellois'},
  {nationality: 'Sierra Leonean'},
  {nationality: 'Singaporean'},
  {nationality: 'Sint Maarten'},
  {nationality: 'Slovak'},
  {nationality: 'Slovenian, Slovene'},
  {nationality: 'Solomon Island'},
  {nationality: 'Somali, Somalian'},
  {nationality: 'South African'},
  {nationality: 'South Georgia or South Sandwich Islands'},
  {nationality: 'South Sudanese'},
  {nationality: 'Spanish'},
  {nationality: 'Sri Lankan'},
  {nationality: 'Sudanese'},
  {nationality: 'Surinamese'},
  {nationality: 'Svalbard'},
  {nationality: 'Swazi'},
  {nationality: 'Swedish'},
  {nationality: 'Swiss'},
  {nationality: 'Syrian'},
  {nationality: 'Chinese, Taiwanese'},
  {nationality: 'Tajikistani'},
  {nationality: 'Tanzanian'},
  {nationality: 'Thai'},
  {nationality: 'Timorese'},
  {nationality: 'Togolese'},
  {nationality: 'Tokelauan'},
  {nationality: 'Tongan'},
  {nationality: 'Trinidadian or Tobagonian'},
  {nationality: 'Tunisian'},
  {nationality: 'Turkish'},
  {nationality: 'Turkmen'},
  {nationality: 'Turks and Caicos Island'},
  {nationality: 'Tuvaluan'},
  {nationality: 'Ugandan'},
  {nationality: 'Ukrainian'},
  {nationality: 'Emirati, Emirian, Emiri'},
  {nationality: 'British, UK'},
  {nationality: 'American'},
  {nationality: 'American'},
  {nationality: 'Uruguayan'},
  {nationality: 'Uzbekistani, Uzbek'},
  {nationality: 'Ni-Vanuatu, Vanuatuan'},
  {nationality: 'Venezuelan'},
  {nationality: 'Vietnamese'},
  {nationality: 'British Virgin Island'},
  {nationality: 'U.S. Virgin Island'},
  {nationality: 'Wallis and Futuna, Wallisian or Futunan'},
  {nationality: 'Sahrawi, Sahrawian, Sahraouian'},
  {nationality: 'Yemeni'},
  {nationality: 'Zambian'},
  {nationality: 'Zimbabwean'},
];

const profile = [
  {
    id: 'FPM609056',
    image:
      'https://i1.wp.com/www.hindishayaricollections.com/wp-content/uploads/2019/09/beautiful-girls-images-wallpapers-6.jpg?resize=652%2C700&ssl=1',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
  {
    id: 'FPM609056',
    image:
      'https://dp.profilepics.in/profile_pictures/village-girl/village-girl-images-81.jpg',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
  {
    id: 'FPM609056',
    image:
      'https://i.pinimg.com/originals/c6/55/a2/c655a22ecb8cbf47b4cf708e8792be66.jpg',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
  {
    id: 'FPM609056',
    image:
      'https://1.bp.blogspot.com/-4l0CGOzR_2s/YGAWcctx5XI/AAAAAAAAVkU/ziLQpEpGhFUyhAyz76IUgaHnEibKanltACLcBGAsYHQ/w528-h640/5.jpg',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
  {
    id: 'FPM609056',
    image:
      'https://i.pinimg.com/originals/8d/4f/9a/8d4f9acba941874b4904e07528d73d02.jpg',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
  {
    id: 'FPM609056',
    image:
      'https://images.unsplash.com/photo-1623091411395-09e79fdbfcf3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Ym9sZCUyMGdpcmx8ZW58MHx8MHx8&w=1000&q=80',
    name: 'Devlina Sarkar',
    gender: 'Female',
    age: '37yrs,',
    height: '162 cm,',
    bodyType: 'Average',
    caste: 'SC,',
    religion: 'Hindu : Brahmin',
    city: 'Kolkata,',
    state: 'West Bengal,',
    country: 'India,',
    education: 'B.A',
  },
];
const text =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
export {
  categories,
  communities,
  createType,
  gender,
  matrialStatus,
  country,
  nationality,
  profile,
  text,
};
