const FONT_SIZE_EXTRA_SMALL = 10;
const FONT_SIZE_SMALL = 12;
const FONT_SIZE_NORMAL = 14;
const FONT_SIZE_MEDIUM = 16;
const FONT_SIZE_LARGE = 18;
const FONT_SIZE_EXTRA_LARGE = 20;

export {
  FONT_SIZE_EXTRA_SMALL,
  FONT_SIZE_SMALL,
  FONT_SIZE_NORMAL,
  FONT_SIZE_MEDIUM,
  FONT_SIZE_LARGE,
  FONT_SIZE_EXTRA_LARGE,
};
